BEGIN TRANSACTION;
CREATE TABLE "STUDENT" (
	"ID"	INT NOT NULL,
	"NAME"	TEXT NOT NULL,
	"SURNAME"	TEXT NOT NULL,
	"GRADYEAR"	INT NOT NULL,
	"MAJOR"	CHAR(4) NOT NULL,
	"EMAIL"	text NOT NULL,
	PRIMARY KEY("ID")
);
CREATE TABLE "INSTRUCTOR" (
	"ID"	INT NOT NULL,
	"NAME"	TEXT NOT NULL,
	"SURNAME"	TEXT NOT NULL,
	"TITLE"	TEXT NOT NULL,
	"HIREYEAR"	INT NOT NULL,
	"DEPT"	CHAR(4) NOT NULL,
	"EMAIL"	text NOT NULL,
	PRIMARY KEY("ID")
);
CREATE TABLE "ADMIN" (
	"ID"	INT NOT NULL,
	"NAME"	TEXT NOT NULL,
	"SURNAME"	TEXT NOT NULL,
	"TITLE"	TEXT NOT NULL,
	"OFFICE"	TEXT NOT NULL,
	"EMAIL"	text NOT NULL,
	PRIMARY KEY("ID")
);

CREATE TABLE "COURSE" (
	"CRN" INT NOT NULL,
	"TITLE" TEXT NOT NULL,
	"DEPARTMENT" TEXT NOT NULL,
	"TIME" TEXT NOT NULL,
	"DAYS" TEXT NOT NULL,
	"SEMESTER" TEXT NOT NULL,
	"YEAR" INT NOT NULL,
	"CREDIT" FLOAT NOT NULL,
	PRIMARY KEY("CRN")
);

INSERT INTO "STUDENT" VALUES (10001,'Isaac','Newton',1668,'BSAS','newtoni');
INSERT INTO "STUDENT" VALUES (10002,'Marie','Curie',1903,'BSAS','curiem');
INSERT INTO "STUDENT" VALUES (10003,'Nikola','Tesla',1878,'BSEE','telsan');
INSERT INTO "STUDENT" VALUES (10004,'Thomas','Edison',1879,'BSEE','notcool');
INSERT INTO "STUDENT" VALUES (10005,'John','von Neumann',1923,'BSCO','vonneumannj');
INSERT INTO "STUDENT" VALUES (10006,'Grace','Hopper',1928,'BCOS','hopperg');
INSERT INTO "STUDENT" VALUES (10007,'Mae','Jemison',1981,'BSCH','jemisonm');
INSERT INTO "STUDENT" VALUES (10008,'Mark','Dean',1979,'BSCO','deanm');
INSERT INTO "STUDENT" VALUES (10009,'Michael','Faraday',1812,'BSAS','faradaym');
INSERT INTO "STUDENT" VALUES (10010,'Ada','Lovelace',1832,'BCOS','lovelacea');
INSERT INTO "INSTRUCTOR" VALUES (20001,'Joseph','Fourier','Full Prof.',1820,'BSEE','fourierj');
INSERT INTO "INSTRUCTOR" VALUES (20002,'Nelson','Patrick','Full Prof.',1994,'HUSS','patrickn');
INSERT INTO "INSTRUCTOR" VALUES (20003,'Galileo','Galilei','Full Prof.',1600,'BSAS','galileig');
INSERT INTO "INSTRUCTOR" VALUES (20004,'Alan','Turing','Associate Prof.',1940,'BSCO','turinga');
INSERT INTO "INSTRUCTOR" VALUES (20005,'Katie','Bouman','Assistant Prof.',2019,'BCOS','boumank');
INSERT INTO "INSTRUCTOR" VALUES (20006,'Daniel','Bernoulli','Associate Prof.',1760,'BSME','bernoullid');
INSERT INTO "ADMIN" VALUES (30001,'Margaret','Hamilton','President','Dobbs 1600','hamiltonm');
INSERT INTO "ADMIN" VALUES (30002,'Vera','Rubin','Registrar','Wentworth 101','rubinv');
COMMIT;
